import { useEffect, useState } from "react";
import heroImage from "../assets/Images/hero.jpg";
import logoImage from "../assets/Images/logo.png";
import haircutImage from "../assets/Images/feature-1.jpg";
import beardImage from "../assets/Images/feature-2.jpg";
import shaveImage from "../assets/Images/feature-3.jpg";
import fadeImage from "../assets/Images/feature-4.jpeg";
import kidsImage from "../assets/Images/kids cut.jpg";
import headShaveImage from "../assets/Images/head shave.jpg";

const services = [
  ["Classic Haircut", "Timeless cuts with modern precision tailored to your style.", haircutImage, 25, true],
  ["Beard Trim", "Shape and line-up your beard for a clean, sharp finish.", beardImage, 15, false],
  ["Straight Razor Shave", "Hot towel treatment with a smooth traditional shave.", shaveImage, 30, true],
  ["Fade & Style", "A clean fade with finishing detail for a sharp, modern look.", fadeImage, 35, false],
  ["Kids Cut", "Clean, comfortable haircut service for younger clients.", kidsImage, 20, false],
  ["Head Shave", "Smooth head shave with classic barbershop treatment.", headShaveImage, 28, true],
].map(([title, description, image, price, popular], id) => ({ id, title, description, image, price, popular, details: [`Consultation for your ${title.toLowerCase()}.`, "Professional tools used for precision.", "Neckline and finishing details included.", "A polished style ready for your day."] }));
const navLinks = [["home", "#hero"], ["services", "#features"], ["book", "#cta"], ["contact", "#footer"]];
const weekdaySlots = ["9:00 AM", "10:00 AM", "11:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM"];
const saturdaySlots = ["10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM"];
const formatKey = (year, month, day) => `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
const readableDate = (year, month, day) => new Date(year, month, day).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" });
const isPast = (year, month, day) => new Date(year, month, day).setHours(0, 0, 0, 0) < new Date().setHours(0, 0, 0, 0);
const isSunday = (year, month, day) => new Date(year, month, day).getDay() === 0;

function Header({ open, setOpen }) {
  return <header className="site-header"><div className="container header-inner"><a href="#hero" className="logo" onClick={() => setOpen(false)}><img src={logoImage} alt="" />Your Vintage Barbershop</a><nav className="nav">{navLinks.map(([label, href]) => <a key={href} href={href} className="nav-link">{label}</a>)}</nav><button className="menu-btn" aria-label="Toggle menu" aria-expanded={open} onClick={() => setOpen(!open)}>☰</button></div><div className={`mobile-menu ${open ? "is-open" : ""}`}>{navLinks.map(([label, href]) => <a key={href} href={href} className="mobile-link" onClick={() => setOpen(false)}>{label}</a>)}</div></header>;
}

function Modal({ service, close }) {
  useEffect(() => { if (!service) return undefined; const escape = (event) => event.key === "Escape" && close(); document.body.style.overflow = "hidden"; document.addEventListener("keydown", escape); return () => { document.body.style.overflow = ""; document.removeEventListener("keydown", escape); }; }, [service, close]);
  if (!service) return null;
  return <div className="service-modal is-open"><div className="service-modal-overlay" onClick={close} /><div className="service-modal-content" role="dialog" aria-modal="true" aria-labelledby="serviceModalTitle"><button className="service-modal-close" aria-label="Close modal" onClick={close}>×</button><h3 id="serviceModalTitle">{service.title}</h3><p className="service-modal-price">${service.price}</p><ul className="service-modal-list">{service.details.map((detail) => <li key={detail}>{detail}</li>)}</ul></div></div>;
}

function Booking() {
  const today = new Date();
  const [viewDate, setViewDate] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selected, setSelected] = useState(null);
  const [time, setTime] = useState("");
  const [booked, setBooked] = useState({ "2026-03-28": ["10:00 AM", "2:00 PM"] });
  const [form, setForm] = useState({ name: "", service: "" });
  const [message, setMessage] = useState({ text: "", type: "" });
  const year = viewDate.getFullYear(); const month = viewDate.getMonth(); const firstDay = new Date(year, month, 1).getDay(); const days = new Date(year, month + 1, 0).getDate();
  const selectedKey = selected ? formatKey(selected.year, selected.month, selected.day) : "";
  const slots = selected ? (new Date(selected.year, selected.month, selected.day).getDay() === 6 ? saturdaySlots : weekdaySlots) : [];
  const chooseDate = (day) => { if (isPast(year, month, day) || isSunday(year, month, day)) return; setSelected({ year, month, day }); setTime(""); setMessage({ text: "", type: "" }); };
  const submit = (event) => { event.preventDefault(); if (!form.name.trim() || !form.service || !selected || !time) { setMessage({ text: "Please choose a date, time, name, and service", type: "error" }); return; } if ((booked[selectedKey] || []).includes(time)) { setMessage({ text: "The time was just taken. Please choose another.", type: "error" }); return; } setBooked({ ...booked, [selectedKey]: [...(booked[selectedKey] || []), time] }); setMessage({ text: `${form.name.trim()}, your ${form.service} appointment is booked for ${readableDate(selected.year, selected.month, selected.day)} at ${time}`, type: "success" }); setTime(""); };
  return <div className="container booking-layout"><div className="calendar-card"><div className="calendar-header"><button className="calendar-nav-btn" aria-label="Previous month" onClick={() => setViewDate(new Date(year, month - 1, 1))}>←</button><h3>{viewDate.toLocaleDateString("en-US", { month: "long", year: "numeric" })}</h3><button className="calendar-nav-btn" aria-label="Next month" onClick={() => setViewDate(new Date(year, month + 1, 1))}>→</button></div><div className="calendar-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{Array.from({ length: firstDay }, (_, index) => <div className="calendar-empty" key={`empty-${index}`} />)}{Array.from({ length: days }, (_, index) => { const day = index + 1; const key = formatKey(year, month, day); const disabled = isPast(year, month, day) || isSunday(year, month, day); return <button key={key} className={`calendar-day ${day === today.getDate() && month === today.getMonth() && year === today.getFullYear() ? "today" : ""} ${selectedKey === key ? "selected" : ""}`} disabled={disabled} onClick={() => chooseDate(day)}>{day}</button>; })}</div></div><div className="booking-panel"><h3 className="booking-panel-title">Book Your Appointment</h3><p className="selected-date-text">Selected Date: <span>{selected ? readableDate(selected.year, selected.month, selected.day) : "Choose a date"}</span></p><div className="time-slots">{!selected && <p className="selected-data-text">Choose a date first.</p>}{selected && slots.map((slot) => { const unavailable = (booked[selectedKey] || []).includes(slot); return <button type="button" key={slot} className={`time-slot-btn ${time === slot ? "selected" : ""} ${unavailable ? "disabled" : ""}`} disabled={unavailable} onClick={() => setTime(slot)}>{unavailable ? `${slot} - Booked` : slot}</button>; })}</div><form className="booking-form" onSubmit={submit}><div className="form-group"><label htmlFor="customerName">Name</label><input id="customerName" value={form.name} placeholder="Enter your name" onChange={(event) => setForm({ ...form, name: event.target.value })} /></div><div className="form-group"><label htmlFor="customerService">Service</label><select id="customerService" value={form.service} onChange={(event) => setForm({ ...form, service: event.target.value })}><option value="">Choose a service</option>{services.slice(0, 4).map((service) => <option key={service.id} value={service.title}>{service.title}</option>)}</select></div><button type="submit" className="btn btn-primary booking-submit-btn">Confirm Booking</button><p className={`booking-message ${message.type}`}>{message.text}</p></form></div></div>;
}

export default function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [modal, setModal] = useState(null); const [heading, setHeading] = useState("Classic Cuts. Clean Shaves. Vintage Style.");
  return <><Header open={menuOpen} setOpen={setMenuOpen} /><main><section className="hero" id="hero"><div className="container hero-inner"><div className="hero-text"><h1>{heading}</h1><p>Experience the tradition of a true barbershop-precision fades, straight-razor shaves, and a welcoming atmosphere.</p><div className="hero-actions"><a href="#cta" className="btn btn-primary">Book an Appointment</a><a href="#features" className="btn btn-secondary">View Services</a></div></div><div className="hero-media"><img src={heroImage} alt="Barbershop hero" className="hero-img" /></div></div></section><section className="features" id="features"><div className="container"><h2 className="section-title">Services</h2><p className="section-subtitle">Quality grooming services designed for comfort, style, and confidence.</p><div className="feature-grid">{services.map((service) => <article className="feature-card" key={service.id}><img src={service.image} alt={service.title} className="feature-img" /><h3 className="feature-title">{service.title}</h3><p className="feature-text">{service.description}</p><p className={`service-badge ${service.popular ? "" : "alt-badge"}`}>{service.popular ? "Popular Choice" : "Barber Favorite"}</p><p className="service-price">${service.price}</p><div className="service-actions"><button className="service-details-btn" type="button" onClick={() => setModal(service)}>View Details</button></div></article>)}</div></div></section><section className="cta" id="cta"><div className="container cta-inner"><div className="cta-text"><h2>Ready for a fresh look?</h2><p>Walk-ins welcome, appointments recommended. Book Today.</p></div><div className="cta-actions"><button className="btn btn-primary" onClick={() => document.getElementById("customerName")?.focus()}>Book Now</button><button className="btn btn-secondary" onClick={() => setHeading("Call us at (555) 123-4567")}>Call Us</button></div></div><Booking /></section></main><footer className="site-footer" id="footer"><div className="container footer-inner"><div className="footer-col"><h3 className="footer-title">Vintage Barbershop</h3><p className="footer-text">Old-school service. Modern craftsmanship.</p></div><div className="footer-col"><h4 className="footer-heading">Hours</h4><ul className="footer-list"><li>Mon-Fri: 9am - 7pm</li><li>Sat: 10am - 5pm</li><li>Sun: Closed</li></ul></div><div className="footer-col"><h4 className="footer-heading">Contact</h4><ul className="footer-list"><li><a href="#footer" className="footer-link">123 Main St, Your City</a></li><li><a href="tel:5551234567" className="footer-link">(555) 123-4567</a></li><li><a href="mailto:hello@vintagebarbershop.com" className="footer-link">hello@vintagebarbershop.com</a></li></ul></div></div><div className="container footer-bottom"><p className="copyright">© {new Date().getFullYear()} Vintage Barbershop. All rights reserved.</p></div></footer><Modal service={modal} close={() => setModal(null)} /></>;
}
